### ISSUE TITLE
Offboard departing GC members and Onboard new GC members

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/community#1494]
List of tasks to do, based on previous year #1169:

- [x] Create a new GC meeting with the new members
- [x] Add new GC members to slack channels
  - [x] #opentelemetry-gc
  - [x] #opentelemetry-gc-tc
- [x] Encourage outgoing GC members to join #opentelemetry-gc-alum
- [x] Add new GC members to mailing lists
  - [x] https://lists.cncf.io/g/cncf-opentelemetry-governance
  - [x] https://lists.cncf.io/g/cncf-opentelemetry-maintainers
  - [x] https://lists.cncf.io/g/cncf-otel-zoomadmins
- [x] Remove outoing GC members from mailing lists
  - [x] https://lists.cncf.io/g/cncf-opentelemetry-governance
  - [x] https://lists.cncf.io/g/cncf-opentelemetry-maintainers
  - [x] https://lists.cncf.io/g/cncf-otel-zoomadmins
- [x] Add new members to github team https://github.com/orgs/open-telemetry/teams/governance-committee/members
- [x] Remove outoing members from github team https://github.com/orgs/open-telemetry/teams/governance-committee/members
- [x] Invite to 1password
  - [x] Add to GC group in 1password
  - Process: invite to 1password account by email. After they accept the invite you should confirm their membership. You will then be able to add them to the "Owners" group which should contain only GC members. Verify they have access to the Governance vault.
- [x] Revoke GC 1password access from outgoing members
- [x] Update official CNCF maintainers list https://github.com/cncf/foundation/blob/main/project-maintainers.csv
  - https://github.com/cncf/foundation/pull/661
- [x] grant new GC members write permissions to GC meeting notes: https://docs.google.com/document/d/1-23Sf7-xZK3OL5Ogv2pK0NP9YotlSa0PKU9bvvtQwp8/edit
- [x] revoke outoing GC members' write permission to GC meeting notes
- [x] Update the community-members.md and and codeowners: https://github.com/open-telemetry/community/
  - https://github.com/open-telemetry/community/pull/1760
- [x] Add to this group, so that they can add calendar events https://groups.google.com/g/opentelemetry-calendar-contributors
- [ ] Rotate important passwords

**Comment by dyladan** [comment]
Congratulations @svrnm and @danielgblanco! 🎉 

Please reach out to me (Daniel Dyla) on slack so that I can get you onboarded.

**Comment by dyladan** [comment]
Congratulations to you as well @austinlparker!

**Comment by dyladan** [comment]
It seems I don't have admin permission on https://lists.cncf.io/g/cncf-opentelemetry-maintainers

Possibly that is maintained by the CNCF and is already fixed by https://github.com/cncf/foundation/pull/661?

**Comment by trask** [comment]
based on https://github.com/cncf/foundation#other-content it looks like we still need to raise a service desk ticket:

> The list of maintainers for each CNCF project is held in the [project-maintainers.csv](https://github.com/cncf/foundation/blob/main/project-maintainers.csv) file. An existing project maintainer can update this list by Pull Request, and they should also email [cncf-maintainer-changes@cncf.io](mailto:cncf-maintainer-changes@cncf.io) (or raise a service desk ticket) to request corresponding changes to the project's CNCF-run maintainer mailing list.

**Comment by svrnm** [comment]
I think I am still not member of [opentelemetry-calendar-contributors](https://groups.google.com/g/opentelemetry-calendar-contributors)

**Comment by danielgblanco** [comment]
You should be there now @svrnm. What I don't know if we should be have the owner role on that group, or if the only owner is opentelemetry.calendar.owner@gmail.com

**Comment by trask** [comment]
the group for the calendar is now [calendar-edit-permission@opentelemetry.io](https://groups.google.com/a/opentelemetry.io/g/calendar-edit-permission)

I sent #1950 to fix the gc onboarding doc since that was merged before #1788.

> What I don't know if we should be have the owner role on that group

since the GC has access to admin@opentelemetry.io, I think that may be enough, but it's not a problem if we want GC members to be individually listed as group owners

**Comment by danielgblanco** [comment]
Closing this issue after GC meeting. We have the new onboarding issue template to list new steps.

**Comment by svrnm** [comment]
thank you for driving this to closure, @danielgblanco !:-)
