### ISSUE TITLE
REQUEST: Repository maintenance on opentelemetry-rust

### ISSUE THREAD

**Issue by cijothomas** [open-telemetry/community#2021]
### Affected Repository

https://github.com/open-telemetry/opentelemetry-rust
https://github.com/open-telemetry/opentelemetry-rust-contrib

### Requested changes

Grant `OpenTelemetryMaintainer` access for @open-telemetry/rust-maintainers 

### Purpose

The maintainers currently do not have access to this repo to make certain CI checks *required*, thereby accidently merging PRs with failed CI. We'd like to get permissions to fix this.
 
### Expected Duration

permanently (assume this is accepted practice!)

### Repository Maintainers

@open-telemetry/rust-maintainers

**Comment by trask** [comment]
> assume this is accepted practice!

check out https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#collaborators-and-teams

> If requested, `foo-maintainers` will be granted `Admin` permissions, and in return they must document any changes they make to the repository settings in a file named `.github/repository-settings.md` in their repository (other than temporarily disabling "Do not allow bypassing the above settings").

**Comment by cijothomas** [comment]
@trask Thanks! We don't need admin privileges. We need the `Maintain` permissions only and permanently. I think it was just a bug that maintainers don't have it already!

> The team foo-maintainers has Maintain permissions for the repository

**Comment by trask** [comment]
Oops, yes, thanks

Cc @open-telemetry/technical-committee

**Comment by jack-berg** [comment]
The @open-telemetry/rust-maintainers appear to already have the `Maintain` role for both `opentelemetry-rust` and `opentelemetry-rust-contrib`:

<img width="1320" alt="Screenshot 2024-03-27 at 3 12 26 PM" src="https://github.com/open-telemetry/community/assets/34418638/42dfe775-bbaf-4c0a-b478-efd17f018ebe">
<img width="1324" alt="Screenshot 2024-03-27 at 3 12 16 PM" src="https://github.com/open-telemetry/community/assets/34418638/f403ee9c-5aa1-47ea-bcbb-b86815f640be">

> The maintainers currently do not have access to this repo to make certain CI checks required, thereby accidently merging PRs with failed CI. We'd like to get permissions to fix this.

I don't think that changing the branch protection rules is covered by maintain. See github docs [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule):

> People with admin permissions or a custom role with the "edit repository rules" permission to a repository can manage branch protection rules.

Typically people have either asked for TC to modify those, requested temporary admin to modify themselves, or requested permanent admin access and tracked the diff in `.github/repository-settings.md`.

**Comment by cijothomas** [comment]
Thanks Jack! Let me get back with if we just ask TC to fix the CI checks, or need admin access temporarily and do it outselves.

Separately, something feels off here! Julian has "Maintainer" tag, though all other maintainers are part of the team... Any idea why so!?
<img width="1006" alt="image" src="https://github.com/open-telemetry/community/assets/5232798/af45747b-66e2-4d2a-a11c-c6068622bbe7">


Additionally, an emeritus-approver still in this list:
https://github.com/orgs/open-telemetry/teams/rust-approvers
<img width="886" alt="image" src="https://github.com/open-telemetry/community/assets/5232798/ea601989-183d-45e3-bd5a-5852ea81594d">

But I, as a maintainer, does not seem to have the permission to remove emeritus approvers! And I don't see myself having permission to add someone to approver/maintainer either!

Tagging another maintainer, @TommyCpp, to see if this is just my account.

**Comment by trask** [comment]
> Julian has "Maintainer" tag

this means they are a maintainer of the team, and can add and remove members

it looks like that team wasn't set up quite right, here's how it should be set up: https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#collaborators-and-teams

someone from @open-telemetry/technical-committee can fix that for us

**Comment by hdost** [comment]
One thing we noticed when discussing this the other tday is that there's a "Maintain" and a custom role "OpenTelemetry Maintain" or something similar to that. I'm not sure what permissions that would grant.

**Comment by TommyCpp** [comment]
> Tagging another maintainer, @TommyCpp, to see if this is just my account.

Can confirm I don't have access to manage the account in teams

**Comment by jack-berg** [comment]
> Separately, something feels off here! Julian has "Maintainer" tag, though all other maintainers are part of the team... Any idea why so!?

Fixed, I think something was just botched during initial team setup.

> One thing we noticed when discussing this the other tday is that there's a "Maintain" and a custom role "OpenTelemetry Maintain" or something similar to that. I'm not sure what permissions that would grant.

I'm not sure about the origin of the `OpenTelemetryMaintainer` role, but it appears to be an extension of the base `Maintainer` role. Here is a screenshot of its permissions:

<img width="817" alt="Screenshot 2024-03-29 at 10 29 01 AM" src="https://github.com/open-telemetry/community/assets/34418638/4432b4d3-baf3-48b1-a1dc-541f11264d4f">

I compared to the `Maintainer` role and found the following additions:
- Issue
  - Delete an issue
- Repository
  - Manage deploy keys
  - Manage webhooks
- Security
  - Delete code scanning analyses
  - View secret scanning alerts

I scanned ~10 or so repositories and didn't see `OpenTelemetryMaintainer` used in any of them.

Let me know what you all end up deciding with how you want to proceed with adding these CI checks.

**Comment by cijothomas** [comment]
Thanks Jack. I can confirm it looks correct now for rust-maintainers team.

https://github.com/orgs/open-telemetry/teams/rust-approvers Could you fix this one too, as we still dont have ability to add/remove people here.

(Will get back on the CI check soon)

**Comment by jack-berg** [comment]
> https://github.com/orgs/open-telemetry/teams/rust-approvers Could you fix this one too, as we still dont have ability to add/remove people here.

All set. The `rust-maintainers` now all have the `Maintainer` role  in `rust-approvers`.

**Comment by jack-berg** [comment]
@cijothomas following up on this - are any other changes needed?

**Comment by cijothomas** [comment]
> @cijothomas following up on this - are any other changes needed?

Yes. Can you grant admin access to maintainers. We'll follow the below:

> If requested, foo-maintainers will be granted Admin permissions, and in return they must document any changes they make to the repository settings in a file named .github/repository-settings.md in their repository (other than temporarily disabling "Do not allow bypassing the above settings", see branch protection rules below).

**Comment by cijothomas** [comment]
> repository-settings.md

https://github.com/open-telemetry/opentelemetry-rust/pull/1693
